# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Hatch
      run: pipx install hatch

    # - name: Run tests
    #   uses: hatch run dev:pytest

    - name: Update version in __about__.py
      run: |
        VERSION=${{ github.event.release.tag_name }}
        VERSION=${VERSION#v}  # strip leading "v" if present
        sed -i "s/^__version__ = .*/__version__ = \"${VERSION}\"/" src/hipp/__about__.py

    - name: Build package
      run: hatch build
      
    - name: Publish package distribution to Pypi
      run: hatch publish 
      env: 
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
